### ISSUE TITLE
TRG 5.02 Helm chart location in `/charts` directory and correct structure

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#153]
https://github.com/eclipse-tractusx/managed-identity-wallet/blob/287b61d12cabf7e2a39f60e1f49d9baaa8401e8c/charts/managed-identity-wallet/README.md?plain=1#L5

`charts/managed-identity-wallet/README.md` is outdated and not up to date (at lease the Readme badges on top).

**Comment by pmoscode** [comment]
This should be resolved / updated by #172

**Comment by borisrizov-zf** [comment]
@pmoscode I think we'll have to pull out the update of the `README.md` and create a separate PR. Can you do that?
@carslen ping, just fyi.

**Comment by pmoscode** [comment]
Hi @borisrizov-zf,
the PR wasn't intended to solve this issue. It's a complete isolated PR.
But it solves - as a nice side-effect - this issue too. (At the time of the PR creation)

**Comment by borisrizov-zf** [comment]
The problem stems from the fact that the workflow which validates the version only runs when data changes in the charts/ directory. The workflow which updates the versions in the Chart.yaml doesn't trigger the helm-docs command and in the end this is left out. I've changed it manually for the current release and will fix this in the coming days.

PR #187 resolves this issue for now.

**Comment by carslen** [comment]
I'll leave this topic open, as it isn't solved, even with the 0.3.0 release:

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/01a70fd2659893d4d5f28da160ab84b778386a12/charts/managed-identity-wallet/README.md?plain=1#L5

**Comment by borisrizov-zf** [comment]
The README is not updated whenever a release is done.
